# Generated by Django 5.0 on 2023-12-26 13:14

import AppFormularios.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReempadComercioFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nombreFantasia', models.CharField(max_length=50)),
                ('cuit', models.IntegerField()),
                ('ingresosBrutos', models.IntegerField()),
                ('convenioMultilateral', models.IntegerField(blank=True, null=True)),
                ('domicilioFiscal', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
                ('provincia', models.CharField(max_length=50)),
                ('domicilioComercial', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefonoComercial', models.IntegerField()),
                ('telefonoTitular', models.IntegerField()),
                ('superficieLocal', models.IntegerField()),
                ('superficieDeposito', models.IntegerField(blank=True, null=True)),
                ('actividadPrincipal', models.CharField(max_length=100)),
                ('rubro2', models.CharField(blank=True, max_length=100, null=True)),
                ('rubro3', models.CharField(blank=True, max_length=100, null=True)),
                ('rubro4', models.CharField(blank=True, max_length=100, null=True)),
                ('sucursal', models.BooleanField(default=False)),
                ('domicilioSucursal', models.CharField(blank=True, max_length=50, null=True)),
                ('inscripcionAFIP', models.FileField(blank=True, null=True, upload_to=AppFormularios.models.upload_to_inscripcionAFIP, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='ERROR, el archivo tiene que estar en formato PDF.')])),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppFormularios.estado')),
            ],
        ),
    ]
