# Generated by Django 5.0 on 2023-12-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppFormularios.estado'),
        ),
    ]
