# Generated by Django 4.2.7 on 2023-12-28 22:27

import AppFormularios.models.uploaders
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReempadComercioJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nombreFantasia', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=20)),
                ('ingresosBrutos', models.CharField(max_length=20)),
                ('convenioMultilateral', models.CharField(blank=True, max_length=20, null=True)),
                ('irpc_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('irpc_folio', models.CharField(blank=True, max_length=20, null=True)),
                ('irpc_libro', models.CharField(blank=True, max_length=20, null=True)),
                ('irpc_tema', models.CharField(blank=True, max_length=20, null=True)),
                ('irpc_anio', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilioFiscal', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('codigoPostal', models.IntegerField()),
                ('provincia', models.CharField(max_length=50)),
                ('domicilioComercial', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefonoComercial', models.CharField(max_length=20)),
                ('telefonoTitular', models.CharField(max_length=20)),
                ('superficieLocal', models.IntegerField()),
                ('superficieDeposito', models.IntegerField(blank=True, null=True)),
                ('actividadPrincipal', models.CharField(max_length=100)),
                ('rubro2', models.CharField(blank=True, max_length=100, null=True)),
                ('rubro3', models.CharField(blank=True, max_length=100, null=True)),
                ('rubro4', models.CharField(blank=True, max_length=100, null=True)),
                ('sucursal', models.BooleanField(default=False)),
                ('domicilioSucursal', models.CharField(blank=True, max_length=50, null=True)),
                ('caracter', models.CharField(max_length=100)),
                ('socio1_nombre', models.CharField(max_length=50)),
                ('socio1_apellido', models.CharField(max_length=50)),
                ('socio1_dni', models.CharField(max_length=20)),
                ('socio1_domicilio', models.CharField(max_length=50)),
                ('socio1_caracter', models.CharField(max_length=500)),
                ('socio2_nombre', models.CharField(max_length=50)),
                ('socio2_apellido', models.CharField(max_length=50)),
                ('socio2_dni', models.CharField(max_length=20)),
                ('socio2_domicilio', models.CharField(max_length=50)),
                ('socio2_caracter', models.CharField(max_length=500)),
                ('inscripcionAFIP', models.FileField(upload_to=AppFormularios.models.uploaders.upload_to_inscripcionAFIP_juridica, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='ERROR, el archivo tiene que estar en formato PDF.')])),
                ('pdf', models.FileField(blank=True, null=True, upload_to=AppFormularios.models.uploaders.upload_to_reempadronamiento_juridica)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AppFormularios.estado')),
            ],
        ),
    ]
