# Generated by Django 5.0 on 2023-12-26 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0002_alter_reempadcomerciofisica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
