# Generated by Django 4.2.7 on 2023-12-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0002_reempadcomerciojuridica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio1_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio1_caracter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio1_dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio1_domicilio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio1_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio2_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio2_caracter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio2_dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio2_domicilio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciojuridica',
            name='socio2_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
