# Generated by Django 4.2.7 on 2023-12-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0003_alter_reempadcomerciofisica_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='convenioMultilateral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='cuit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='ingresosBrutos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='telefonoComercial',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='telefonoTitular',
            field=models.CharField(max_length=20),
        ),
    ]
