# Generated by Django 4.2.7 on 2023-12-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0003_alter_reempadcomerciojuridica_socio1_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reempadcomerciofisica',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
