# Generated by Django 4.2.7 on 2023-12-26 18:56

import AppFormularios.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0004_alter_reempadcomerciofisica_conveniomultilateral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reempadcomerciofisica',
            name='inscripcionAFIP',
            field=models.FileField(upload_to=AppFormularios.models.upload_to_inscripcionAFIP, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='ERROR, el archivo tiene que estar en formato PDF.')]),
        ),
    ]
