# Generated by Django 4.2.7 on 2023-12-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0005_rename_apellido_reempadcomerciojuridica_razonsocial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reempadcomerciofisica',
            name='codigo_identificacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
