# Generated by Django 4.2.7 on 2023-12-26 19:22

import AppFormularios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0005_alter_reempadcomerciofisica_inscripcionafip'),
    ]

    operations = [
        migrations.AddField(
            model_name='reempadcomerciofisica',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=AppFormularios.models.upload_to_reempadronamiento_fisica),
        ),
    ]
