# Generated by Django 4.2.7 on 2023-12-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0006_reempadcomerciofisica_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='reempadcomerciofisica',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
