# Generated by Django 4.2.7 on 2023-12-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0006_reempadcomerciofisica_codigo_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reempadcomerciojuridica',
            name='codigo_identificacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
