# Generated by Django 4.2.7 on 2023-12-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0007_reempadcomerciojuridica_codigo_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reempadcomerciojuridica',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
